### PR TITLE
Patch version release did-session@0.1.2

### PR DESCRIPTION
**Pull request by pawartur**
Bumped the version after fixing links to repo in 7f6003d97349812ceb75b5302302998bbcb1e607

### CODE REVIEW

**Review by oed — APPROVED** [review]

**Review by zachferland — APPROVED** [review]
you released? or I should release?

**Comment by pawartur** [comment]
Would be great, if you could release, @zachferland . I actually need to learn how to do this :).

**Comment by oed** [comment]
@zachferland @pawartur would be great if we could create a release guide similar to https://github.com/ceramicnetwork/js-ceramic/blob/develop/DEVELOPMENT.md#creating-a-release

**Comment by pawartur** [comment]
Finally merged this PR, @zachferland . Could you please make the release :) ?

@oed , @zachferland, I'll add the creation of a release guide to our backlog. Thanks for pointing that out!

**Pull request merged**
