### PR TITLE
Feat/solana auth

### PR DESCRIPTION
**Pull request by zachferland**
Adds solana authmethod support. 

Tests skip, until support is added for solana cacao verifier in ceramic.

### CODE REVIEW

**Comment by zachferland** [comment]
Tested skipped test locally against this ceramic pr - https://github.com/ceramicnetwork/js-ceramic/pull/2452

Ceramic PR blocks usage of solana auth method, but can review/merge, then enable and release after

**Comment by zachferland** [comment]
Tested in example, full integration with phantom wallet, works as expected, all set to merge 

(need to add another test env to pull in latest ceramic depends, to enable tests, could do in another pr)

**Review by oed — APPROVED** [review]
lgtm

**Comment by baptistegreve** [comment]
This is "The Merge" I'm looking for 😅

**Pull request merged**
