### PR TITLE
Feat/publish website apps 659

### PR DESCRIPTION
**Pull request by pawartur**
# Prepare to publish the docusaurus website from `./website`

## Description

Followed similar setup from `js-composedb` and the steps described on https://js.org/ (so that we can publish on https://did.js.org).

My understanding is that the next steps after merging this PR should be:
1. Merge `main` to `gh-pages`
2. Create a PR that adds `did.org.js` to the list of supported cnames, analogous to https://github.com/js-org/js.org/blob/master/cnames_active.js#L550 

## How Has This Been Tested?

Describe the tests that you ran to verify your changes. Provide instructions for reproduction.

- [X] Built and tested the website

## Definition of Done

Before submitting this PR, please make sure:

- [X] The work addresses the description and outcomes in the issue
- [X] My code follows conventions, is well commented, and easy to understand
- [X] My code builds and tests pass without any errors or warnings
- [X] I have tagged the relevant reviewers

### CODE REVIEW

**Comment by pawartur** [comment]
Actually, I already created the PR in js-org: https://github.com/js-org/js.org/pull/7540

**Comment by pawartur** [comment]
Closed the PR for dids.js.org and opened the new one for did.js.org: https://github.com/js-org/js.org/pull/7541

**Comment by PaulLeCam** [comment]
> My understanding is that the next steps after merging this PR should be:
> 
>     1. Merge `main` to `gh-pages`

That's not necessary, the added GitHub action will take care of deploying the website to GH pages on every push to `main`.

**Review by PaulLeCam — APPROVED** [review]
LGTM but as commented above, this will start deploying the website on every push to the `main` branch, so if there's anything that should get changed before, better wait until merging this PR.

**Pull request merged**
